language: php

branches:
  except:
  - /^.*-built$/

cache:
  apt: true
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.yarn/node_modules
    - node_modules

matrix:
  include:
  - php: 7.3

addons:
  apt:
    packages:
      # Cypress Dependency
      - libgconf-2-4
services:
  # For WP Cypress
  - docker

before_script:
  - composer global require dealerdirect/phpcodesniffer-composer-installer:0.5.0 wp-coding-standards/wpcs:2.1.1 automattic/vipwpcs:2.0.0

install:
  - nvm install 12.14.1
  - cd $TRAVIS_BUILD_DIR
  - yarn
  - composer install

script:
  - set -e
  - yarn -v
  - yarn wp-cypress start
  - yarn cypress run

after_failure:
  - cat node_modules/@bigbite/wp-cypress/debug.log