version: 2.1

orbs:
  php: circleci/php@1.0.1
  node: circleci/node@4.0.0

workflows:
  lint-and-test:
    jobs:
      - tests


jobs:
  tests:
    executor: php/default
    steps:
      - setup_remote_docker
      - checkout
      - php/install-composer
      - php/install-packages
      - node/install:
          install-yarn: true

      - run:
          name: Yarn install
          command: yarn install  
      - run:
          name: Start wp-cypress
          command: yarn run wp-cypress start --no-volumes
      - run:
          name: Run tests
          command: yarn run cypress run